RustAudio/rust-jack

- Cargo.toml
- example/src/main.rs
- src/callbacks.rs
- src/client.rs
- src/enums.rs
- src/flags.rs
- src/info.rs
- src/lib.rs
- src/port.rs
- src/test.rs
Reworked `Port`, `Client` and `JackHandler` to allow for safe access to the input and output buffers in the `process` callback function. Split up `Client` into `Client` and `ActiveClient` to prevent modification to `Client` while audio is being processed.
@wmedrano I haven't had a chance to do a final pass-through and cleanup, but I'm at a point now where I'd appreciate your thoughts when you get a chance to glance through.
> [WIP] Safe Port / buffer access

- README.md
- src/test/test_client_cback.rs
- src/test/test_client_port.rs
* Prevents developers from having to set RUST_TEST_THREADS environment variable
* Dramatically improves test time, from `100s` to `20s` on my system.
> Allow tests to run in parallel

- src/client/async_client.rs
- src/client/base.rs
- src/client/callbacks.rs
This PR would close issue #71 
Implemented Sync to allow passing Client and AsyncClient between threads safely (compiler allows it)
> Implement Send for Client and AsyncClient (#71)

- src/client/callbacks.rs
- src/jack_utils.rs
- src/logging.rs
- src/port/port.rs
fixes compilation errors on ARM platforms where chars are u8, libc::c_char is defined appropriately for the architecture.
> Fix for issue #74 compile on ARM

- src/jack_enums.rs
This implements the [`std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html) trait, so that easy usage of the `?` is possible. It is just a very basic implementation that uses the derived `Debug`-formatter. This could be improved (marked with a `FIXME`).
> Implement std::error::Error

- Cargo.toml
- README.md
- examples/sine.rs
- src/client/async_client.rs
- src/client/callbacks.rs
- src/client/client.rs
- src/lib.rs
- src/port/audio.rs
- src/port/midi.rs
Addresses some concerns in #104
> Add Sync requirement to handlers.

- src/client/async_client.rs
- src/client/callbacks.rs
- src/client/client.rs
- src/jack_enums.rs
- src/port/port.rs
This partially reverts 356aec6c.
A ProcessHandler is moved into `activate_async` and thus can only be used by a single client.
While in Jack2, process_callbacks of *different* clients can indeed run concurrently, the process_callback of a single client can not be concurrent with itself.
(The process_callback of a single client can run concurrently with the notification callbacks of the same client, and I am not sure whether the *notification* callback is also guaranteed to be non-self-concurrent.)
> Remove Sync requirement from ProcessHandler. (#121)

- jack-sys/README.md
First, thank you for your work on this repo!  I've been writing a jack utility this week, and this repo allowed me to do it in rust :slightly_smiling_face: 
I noticed the `jack-sys` README had some formatting issues, and an invalid link to `rust-bindgen`, so went ahead and fixed those.  Take care!
> Correct jack-sys README formatting

- jack-sys/src/lib.rs
This eliminates an allocation in the callback on first call to `jack_get_cycle_times` due to `libloading` needing to null terminate the library name itself.
I didn't do the same to the Windows version because, currently, `libloading` allocates a new buffer for the library file name no matter what; [see here.](https://github.com/nagisa/rust_libloading/blob/1de6189e47aef48d5fbd994063f2e22b94af4e65/src/os/windows/mod.rs#L131)
Tested by using a [custom global allocator](https://github.com/ischeinkman/redes/blob/master/src/malloc.rs) that panics in the RT thread.
> Added null terminator to UNIX shared library name.

- examples/set_transport.rs
- examples/show_transport.rs
- ffi_completeness.md
- src/client/client.rs
- src/lib.rs
- src/transport.rs
No slow sync or timebase master yet, but these bindings give the ability to get transport information and control the transport.
I changed some naming a bit to make more sense to me, but if others thing that we should change those names back (sig_num, sig_denom, etc) I'm willing to.
The `TransportBBT` struct can act like a builder, it does allow you to set it into an invalid state, but there is a validator so I figured that was good enough. The validator could use more error messages but the jack::Error enum didn't provide for that so it just returns a generic error when, for instance, a beat value is out of range.
> transport query and control

- Cargo.toml
- ffi_completeness.md
- jack-sys/Cargo.toml
- jack-sys/src/lib.rs
- src/client/client.rs
- src/client/test.rs
- src/lib.rs
- src/properties.rs
Mostly behind a feature flag since it isn't supported until 1.9.13.
Not all of the property methods actually require a client but it felt more ergonomic to have them be consistent and make them methods on a client.
> optional metadata support

- examples/playback_capture.rs
- src/client/callbacks.rs
- src/client/test_callback.rs
Implements the change discussed in #137. I also added a test to check the assumption that `buffer_size` is called on the same thread as `process`.
This is a breaking change but I did not change the version yet.
> Move buffer_size callback to ProcessHandler

- README.md
Certificates seem to be configured incorrectly for www.jackaudio.org, but not jackaudio.org, so I updated the README to point there. (Also, they seem to use the non-www version as their canonical URL anyway.)
> Change www.jackaudio.org -> jackaudio.org

- jack-sys/Cargo.toml
- jack-sys/build.rs
This fixes linking with PipeWire's JACK headers.
Fixes #142
> jack-sys: search for jack library with pkg-config

- .github/workflows/rust.yml
- Cargo.toml
- jack-sys/Cargo.toml
- jack-sys/src/lib.rs
- src/client/client_impl.rs
- src/port/midi.rs
- src/port/port_impl.rs
Supports #159 for `jack-sys`. Follow up is to use `dlib` in `jack`.
> Add dlib support for jack-sys.

- Cargo.toml
jack 0.9.1 was published depending on jack-sys 0.3.3, which breaks
using the RUST_JACK_DLOPEN environment variable to activate the
dlopen feature.
> bump jack's dependency on jack-sys

- src/client/callbacks.rs
- src/client/client_impl.rs
- src/port/port_impl.rs
- src/transport.rs
This pull request contains two commits:
* The first adds bindings to inspect the state of the JACK server, such as enumerating the clients connected to a given port
* The second allows writing slow-sync clients.  As registering a sync handler at all changes JACK's behavior, this is gated by the new `ProcessHandler::SLOW_SYNC` constant.
I have been using these changes in my own project for a while now and they appear to work properly, but I don't know what unit tests should be added for them.
> Add introspection bindings and support for slow-sync clients

- Cargo.toml
- jack-sys/Cargo.toml
- jack-sys/build.rs
- jack-sys/src/lib.rs
- src/client/client_impl.rs
- src/client/test_callback.rs
- src/port/audio.rs
- src/port/port_impl.rs
- src/properties.rs
- src/transport.rs
In addition to dynamic loading.
> Support dynamic linking

- src/client/client_impl.rs
- src/jack_enums.rs
This fixes #176. Check the issue for more details.
> Return an error instead of panicking when the JACK library doesn't exist or couldn't be loaded

- jack-sys/Cargo.toml
- jack-sys/build.rs
- jack-sys/src/lib.rs
Makes it so that dynamic loading does not need to have the library dev files in order to compile.
> Only link necessary functions.

- Cargo.toml
- src/client/client_impl.rs
- src/port/port_impl.rs
- src/port/test_port.rs
- src/properties.rs
Uses port type from JACK instead of from the spec and adds is_monitoring field.
> Improve port debug output.

- src/client/client_impl.rs
Move error and info logs printouts to after we have connected the client.
Before this change the console was spammed with error logs if the connection(s) failed with no way to silence it. 
The return Result from the connection attempt could be used to catch the failure and then you can print something, if desired. Else it should be quiet.
> silence logs before connected

- src/client/client_impl.rs
Remove assert that connection closing is successful. 
If the jack server is shutdown/restarted while the client connection is up then the closing will fail and you get a thread panic from the assert. 
Furthermore the whole client is forever "bricked" since the assert will happen while holding the CREATE_OR_DESTROY_CLIENT_MUTEX.lock(). The mutex will get a PoisonError which prevents a new client connection to be created again. The mutex is a lazy_static "singleton" so it prevents ANY client to be created for the duration of the application.
> best effort close client

- Cargo.toml
- examples/playback_capture.rs
- src/client/async_client.rs
- src/client/callbacks.rs
- src/client/test_callback.rs
- Marks shutdown as unsafe and links to details about posix signal handling. Closes #106 
- Deactivating will leak the callback objects if there is a panic.
> Make safer.

- src/client/async_client.rs
the deadlock happend because clientcontext was dropped if an error emerged.
> fix deadlock issue #219
